import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#4d4635',
        'surface-tint': '#e9c349',
        'inverse-surface': '#e2e2e2',
        'on-background': '#e2e2e2',
        'on-secondary-container': '#b7b5b4',
        'surface-container-highest': '#333535',
        'on-secondary': '#313030',
        'primary': '#f2ca50',
        'primary-container': '#d4af37',
        'surface-container-lowest': '#0c0f0f',
        'secondary': '#c8c6c5',
        'background': '#121414',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-primary-fixed-variant': '#574500',
        'on-primary-fixed': '#241a00',
        'tertiary-container': '#b5b2b2',
        'surface-container-low': '#1a1c1c',
        'outline': '#99907c',
        'surface': '#121414',
        'on-surface-variant': '#d0c5af',
        'on-tertiary-fixed-variant': '#474646',
        'inverse-primary': '#735c00',
        'on-primary-container': '#554300',
        'secondary-fixed-dim': '#c8c6c5',
        'error-container': '#93000a',
        'secondary-container': '#474746',
        'surface-bright': '#37393a',
        'tertiary-fixed': '#e5e2e1',
        'on-primary': '#3c2f00',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'surface-variant': '#333535',
        'surface-container-high': '#282a2b',
        'on-tertiary': '#313030',
        'on-secondary-fixed-variant': '#474746',
        'surface-dim': '#121414',
        'primary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#1c1b1b',
        'primary-fixed': '#ffe088',
        'on-tertiary-container': '#454545',
        'inverse-on-surface': '#2f3131',
        'secondary-fixed': '#e5e2e1',
        'surface-container': '#1e2020',
        'on-surface': '#e2e2e2',
        'tertiary': '#d0cecd',
        'on-secondary-fixed': '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'container-max': '1200px',
        'unit': '8px',
        'gutter': '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'section-gap': '80px',
        'stack-lg': '32px',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        h1: ['"Noto Serif"', 'Georgia', 'serif'],
        h2: ['"Noto Serif"', 'Georgia', 'serif'],
        h3: ['"Noto Serif"', 'Georgia', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'button': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'button': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
